// ignore_for_file: file_names

List<Map<String, String>> salonFeatures = [
  {"covidVaccinated": "Covid Vaccinated"},
  {"masterWithHearingDisability": "Master With Hearing Disability"},
  {"masterWithSpeechDisability": "Master With Speech Disability"},
  {"medicalDegree": "Medical Degree"},
  {"instrumentSterilization": "Instruments Sterilization"},
  {"antiCovidMeasures": "Anti Covid Measures"},
  {"disposableMaterialsOnly": "Disposable Materials Only"},
  {"coffee": "Coffee"},
  {"cocktails": "cocktails"},
  {"shop": "shop"},
  {"parallelService": "Parallel Service"},
  {"childrenRoom": "Children Room"},
  {"wifi": "Wifi"},
  {"ownOffice": "Own Office"},
  {"womanOwnedBusiness": "Woman Owned Business"},
  {"parking": "Parking"},
  {"masterWithHearingDisability": "Master With Hearing Disability"},
  {"petFriendly": "Pet Friendly"},
  {"noPet": "No Pets"},
  {"medicalPracticeLicense": "Medical Practice License"},
  {"accessibilityForPersonsWithReducedMobility": "Accessibility For Persons With ReducedMobility"},
];

List<Map<String, String>> ukSalonFeatures = [
  {"covidVaccinated": "Ковід Вакцинований"},
  {"masterWithHearingDisability ": "Майстер з вадами слуху"},
  {"masterWithSpeechDisability ": "Майстер з вадами мовлення"},
  {"medicalDegree": "Медичний ступінь"},
  {"instrumentSterilization": "Стерилізація інструментів"},
  {"antiCovidMeasures": "Антиковідні заходи"},
  {"disposableMaterialsOnly": "Лише одноразові матеріали"},
  {"coffee": "кава"},
  {"wifi": "Wi-Fi"},
  {"ownOffice": "Власний кабінет"},
  {"parking": "Паркінг"},
  {"masterWithHearingDisability": "Майстер з вадами слуху"},
  {"petFriendly": "Допускається розміщення з домашніми тваринами"},
  {"noPet": "Без домашніх тварин"},
  {"accessibilityForPersonsWithReducedMobility": "Доступність для осіб з обмеженими можливостями пересування"},
  {"medicalPracticeLicense": "Ліцензія на медичну практику"},
];

List<Map<String, String>> esSalonFeatures = [
  {"covidVaccinated": "Vacunados contra el Covid"},
  {"masterWithHearingDisability": "Maestro con discapacidad auditiva"},
  {"masterWithSpeechDisability": "Maestro con discapacidad del habla"},
  {"medicalDegree": "Título médico"},
  {"instrumentSterilization": "Esterilización de instrumentos"},
  {"antiCovidMeasures": "Medidas Anti Covid"},
  {"disposableMaterialsOnly": "Solo materiales desechables"},
  {"coffee": "Café"},
  {"cocktails": "cócteles"},
  {"shop": "tienda"},
  {"parallelService": "Servicio paralelo"},
  {"childrenRoom": "Habitación de niños"},
  {"wifi": "wifi"},
  {"ownOffice": "Oficina propia"},
  {"womanOwnedBusiness": "Empresa propiedad de una mujer"},
  {"parking": "Estacionamiento"},
  {"masterWithHearingDisability": "Maestro con discapacidad auditiva"},
  {"petFriendly": "Se admiten mascotas"},
  {"noPet": "No se admiten mascotas"},
  {"medicalPracticeLicense": "Licencia de práctica médica"},
  {"accessibilityForPersonsWithReducedMobility": "Accesibilidad para personas con movilidad reducida"},
];

List<Map<String, String>> frSalonFeatures = [
  {"covidVaccinated": "Covid vacciné"},
  {"masterWithHearingDisability": "Maître avec un handicap auditif"},
  {"masterWithSpeechDisability": "Maître atteint d'un trouble de la parole"},
  {"medicalDegree": "Diplôme de médecine"},
  {"instrumentSterilization": "Stérilisation des instruments"},
  {"antiCovidMeasures": "Mesures anti Covid"},
  {"disposableMaterialsOnly": "Matériaux jetables uniquement"},
  {"coffee": "Café"},
  {"cocktails": "cocktails"},
  {"shop": "boutique"},
  {"parallelService": "Service parallèle"},
  {"childrenRoom": "Chambre d'enfants"},
  {"wifi": "Wifi"},
  {"ownOffice": "Propre bureau"},
  {"womanOwnedBusiness": "Entreprise appartenant à une femme"},
  {"parking": "Stationnement"},
  {"masterWithHearingDisability": "Maître avec un handicap auditif"},
  {"petFriendly": "Animaux acceptés"},
  {"noPet": "Pas d'animaux"},
  {"medicalPracticeLicense": "Licence de pratique médicale"},
  {"accessibilityForPersonsWithReducedMobility": "Accessibilité pour les personnes à mobilité réduite"},
];

List<Map<String, String>> ptSalonFeatures = [
  {"covidVaccinated": "Covid Vaccinated"},
  {"masterWithHearingDisability": "Mestre com deficiência auditiva"},
  {"masterWithSpeechDisability": "Mestre com deficiência de fala"},
  {"medicalDegree": "Graduação em Medicina"},
  {"instrumentSterilization": "Esterilização de instrumentos"},
  {"antiCovidMeasures": "Medidas Anti-Covid"},
  {"disposableMaterialsOnly": "Somente materiais descartáveis"},
  {"coffee": "Café"},
  {"cocktails": "coquetéis"},
  {"shop": "loja"},
  {"parallelService": "Serviço Paralelo"},
  {"childrenRoom": "Quarto das Crianças"},
  {"wifi": "Wi-fi"},
  {"ownOffice": "Próprio Escritório"},
  {"womanOwnedBusiness": "Empresa de propriedade de uma mulher"},
  {"parking": "Estacionamento"},
  {"masterWithHearingDisability": "Mestre com deficiência auditiva"},
  {"petFriendly": "Aceita animais de estimação"},
  {"noPet": "Sem animais de estimação"},
  {"medicalPracticeLicense": "Licença para prática médica"},
  {"accessibilityForPersonsWithReducedMobility": "Acessibilidade para pessoas com mobilidade reduzida"},
];

List<Map<String, String>> roSalonFeatures = [
  {"covidVaccinated": "Covid Vaccinated"},
  {"masterWithHearingDisability": "Master With Hearing Disability"},
  {"masterWithSpeechDisability": "Maestru cu dizabilități de vorbire"},
  {"medicalDegree": "Licență medicală"},
  {"instrumentSterilization": "Sterilizarea instrumentelor"},
  {"antiCovidMeasures": "Măsuri anti Covid"},
  {"disposableMaterialsOnly": "Numai materiale de unică folosință"},
  {"coffee": "Coffee"},
  {"cocktails": "cocktail-uri"},
  {"shop": "shop"},
  {"parallelService": "Serviciu paralel"},
  {"childrenRoom": "Camera copiilor"},
  {"wifi": "Wifi"},
  {"ownOffice": "Propriul birou"},
  {"womanOwnedBusiness": "Afacere deținută de femei"},
  {"parking": "Parcare"},
  {"masterWithHearingDisability": "Master With Hearing Disability"},
  {"petFriendly": "Acceptă animalele de companie"},
  {"noPet": "Fără animale de companie"},
  {"medicalPracticeLicense": "Licență de practică medicală"},
  {"accessibilityForPersonsWithReducedMobility": "Accesibility For Persons With ReducedMobility"},
];

List<Map<String, String>> arSalonFeatures = [
  {"covidVaccinated": "تم تلقيح كوفيد"},
  {"masterWithHearingDisability": "ماجستير ذو إعاقة سمعية"},
  {"masterWithSpeechDisability": "رئيسي يعاني من إعاقة في النطق"},
  {"medicalDegree": "الدرجة الطبية"},
  {"instrumentSterilization": "تعقيم الأدوات"},
  {"antiCovidMeasures": "تدابير مكافحة كوفيد"},
  {"disposableMaterialsOnly": "المواد التي يمكن التخلص منها فقط"},
  {"coffee": "قهوة"},
  {"shop": "كوكتيلات"},
  {"parallelService": "الخدمة الموازية"},
  {"childrenRoom": "غرفة الأطفال"},
  {"wifi": "واي فاي"},
  {"ownOffice": "المكتب الخاص"},
  {"womanOwnedBusiness": "مشروع تجاري مملوك لامرأة"},
  {"parking": "موقف سيارات"},
  {"masterWithHearingDisability": "ماجستير ذو إعاقة سمعية"},
  {"petFriendly": "ملائم للحيوانات الأليفة"},
  {"noPet": "ممنوع الحيوانات الأليفة"},
  {"medicalPracticeLicense": "ترخيص الممارسة الطبية"},
  {"accessibilityForPersonsWithReducedMobility": "إمكانية الوصول للأشخاص ذوي القدرة المحدودة على الحركة"},
];

List<Map<String, String>> masterFeatures = [
  {"masterWithHearingDisability": "Master With Hearing Disability"},
  {"masterWithSpeechDisability": "Master With Speech Disability"},
  {"instrumentsSterilization": "Instrument Sterilization"},
  {"antiCovidMeasures": "Anti Covid Measures"},
  {"disposableMaterialsOnly": "Disposable Materials Only"},
  {"womanOwnedBusiness": "Woman Owned Business"},
  {"coffee": "Coffee"},
  {"cocktails": "Cocktails"},
  {"ownOffice": "Own Office"},
  {"medicalDegree": "Medical Degree"},
  {"wifi": "Wifi"},
  {"parking": "Parking"},
  {"shop": "Shop"},
  {"childrenRoom": "Children Room"},
  {"petFriendly": "Pet Friendly"},
  {"noPets": "No Pet"},
  {"covidVaccinated": "Covid Vaccinated"},
  {"accessibilityForPersonsWithReducedMobility": "Accessibility For Persons With ReducedMobility"},
  {"parallelService": "Parallel Service"},
  {"medicalPracticeLicense": "Medical Practice License"},
];

List<Map<String, String>> ukMasterFeatures = [
  {"masterWithHearingDisability": "Майстер з порушення слуху"},
  {"masterWithSpeechDisability": "Майстер з порушенням мовлення"},
  {"ownOffice": "Власний кабінет"},
  {"instrumentsSterilization": "Стерилізація інструментів"},
  {"antiCovidMeasures": "Антиковідні заходи"},
  {"disposableMaterialsOnly": "Лише одноразові матеріали"},
  {"womanOwnedBusiness": "Жіночий бізнес"},
  {"coffee": "Кава/Чай"},
  {"medicalDegree": "Медична освіта"},
  {"cocktails": "Коктейлі"},
  {"covidVaccinated": "Вакцинованість проти Covid-19"},
  {"wifi": "Wi-Fi"},
  {"parking": "Паркінг"},
  {"shop": "Магазин"},
  {"childrenRoom": "Дитяча кімната"},
  {"petFriendly": "Допускається розміщення з домашніми тваринами"},
  {"noPets": "Без тварин"},
  {"accessibilityForPersonsWithReducedMobility": "Доступність для осіб з обмеженими можливостями пересування"},
  {"parallelService": "Паралельний сервіс"},
  {"medicalPracticeLicense ": "Ліцензія на медичну практику"},
];
