name: bbblient
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.4+44

environment:
  sdk: ">=2.17.0 <=3.0.4"

dependencies:
  automatic_animated_list: ^1.0.0
  bot_toast: ^4.0.1
  breakpoint: ^1.2.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^2.3.0
  connectivity_plus: ^2.0.3
  country_code_picker: ^3.0.0
  country_codes: ^2.0.1
  cupertino_icons: ^1.0.3
  device_info: ^2.0.2
  easy_debounce: ^2.0.1
  expandable_page_view: ^1.0.8
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.3.0
  firebase_dynamic_links: ^3.0.1
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.1.0
  web_scroll_flutter:
    git:
      url: https://github.com/Trojan9/web_scroll_flutter.git
      ref: 5f43863 # branch name or commit hash
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: any
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: ^1.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.1.6
  flutter_tags: ^1.0.0-nullsafety.1
  gap: ^2.0.0
  geocoding: ^2.0.1
  geoflutterfire: ^3.0.1
  go_router: ^3.1.0
  google_fonts: ^3.0.1
  dyn_mouse_scroll:
  google_maps_flutter: ^2.1.0
  flutter_spinkit: ^5.2.0
  # google_maps_flutter_web: ^0.3.2+1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+3
  # in_app_update: ^2.0.0
  intl: ^0.17.0
  jiffy: ^4.1.0
  load: ^1.0.0
  #  location: ^4.3.0
  logger: ^1.1.0
  map_launcher: ^2.1.1
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^1.3.0
  paginable: ^1.1.2
  path_provider: ^2.0.5
  permission_handler: ^8.3.0
  pin_code_fields: ^7.3.0
  responsive_builder: ^0.4.1
  share_plus: null
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  show_up_animation: ^2.0.0
  showcaseview: ^1.1.2
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_sliders: ^19.3.46
  table_calendar: ^3.0.3
  top_snackbar_flutter: ^2.1.1
  translator: ^0.1.7
  transparent_image: ^2.0.0
  url_launcher: ^6.1.11
  uuid: ^3.0.5
  vibration: ^1.7.4-nullsafety.0
  google_maps: ^6.2.0
  scrollable_positioned_list: ^0.3.5
  extended_wrap: 0.1.5 
  font_awesome_flutter: ^10.4.0
  maps_launcher: ^2.2.0
  http: ^0.13.6
  flutter_horizontal_date_picker:
  crypto: ^3.0.2
  grouped_list: ^5.1.2
  flutter_staggered_grid_view: ^0.7.0
  screenshot: ^1.3.0
  flutter_dotenv: ^5.1.0
  web_smooth_scroll: ^1.1.0
  marquee: ^2.2.3
  blur: ^3.1.0
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "../logoround.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/test_assets/

    - assets/icons/icons_to_convert/
    - assets/icons/png_icons/
    - assets/icons/features/
    - assets/popups/
    - assets/cards/
    - assets/social_media/

    # Theme Assets
    - assets/themes/glam_one/images/
    - assets/themes/glam_one/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: VASQUZ
      fonts:
        - asset: assets/fonts/VASQUZ-ITALIC.otf
        - asset: assets/fonts/VASQUZ-ITALIC.ttf
        - asset: assets/fonts/VASQUZ.otf
        - asset: assets/fonts/VASQUZ.ttf
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Medium.ttf
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-SemiBold.ttf    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        # - asset: assets/fonts/Inter-Regular.ttf
        # - asset: assets/fonts/Inter-SemiBold.ttf    
        # - asset: assets/fonts/Inter-Bold.ttf    
    - family: UNDERRATED
      fonts:
        - asset: assets/fonts/UNDERRATED.otf
        - asset: assets/fonts/UNDERRATED.otf
        - asset: assets/fonts/UNDERRATED.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Light.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
