// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCMJVcDiTA4TpkUdD3VArn9FxBc-5K7Qgc',
//     appId: '1:1028145974134:web:1d6fa596d538338f760857',
//     messagingSenderId: '1028145974134',
//     projectId: 'bowandbeautiful-3372d',
//     authDomain: 'bowandbeautiful-3372d.firebaseapp.com',
//     databaseURL: 'https://bowandbeautiful-3372d-default-rtdb.firebaseio.com',
//     storageBucket: 'bowandbeautiful-3372d.appspot.com',
//     measurementId: 'G-7RXTJNS2ML',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCM128YfRhmin6kUNttOG5Fs9UZDvI1gLY',
//     appId: '1:1028145974134:android:c59e1b284580a204760857',
//     messagingSenderId: '1028145974134',
//     projectId: 'bowandbeautiful-3372d',
//     databaseURL: 'https://bowandbeautiful-3372d-default-rtdb.firebaseio.com',
//     storageBucket: 'bowandbeautiful-3372d.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBTcLVbQsQ1BX77wizZ8wU5GtJrv0DnD2E',
//     appId: '1:1028145974134:ios:23586fbce2c89432760857',
//     messagingSenderId: '1028145974134',
//     projectId: 'bowandbeautiful-3372d',
//     databaseURL: 'https://bowandbeautiful-3372d-default-rtdb.firebaseio.com',
//     storageBucket: 'bowandbeautiful-3372d.appspot.com',
//     androidClientId: '1028145974134-1u0pk14u1v20ctdoeua7pl3u1ac6ihbv.apps.googleusercontent.com',
//     iosClientId: '1028145974134-9096jaqeggsu68i97roim405m9v8rnsn.apps.googleusercontent.com',
//     iosBundleId: 'com.bnb.client',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBTcLVbQsQ1BX77wizZ8wU5GtJrv0DnD2E',
//     appId: '1:1028145974134:ios:3c4e6d2c51703e37760857',
//     messagingSenderId: '1028145974134',
//     projectId: 'bowandbeautiful-3372d',
//     databaseURL: 'https://bowandbeautiful-3372d-default-rtdb.firebaseio.com',
//     storageBucket: 'bowandbeautiful-3372d.appspot.com',
//     androidClientId: '1028145974134-1u0pk14u1v20ctdoeua7pl3u1ac6ihbv.apps.googleusercontent.com',
//     iosClientId: '1028145974134-kud23rf8a611i4j08kl1mf4014a4imll.apps.googleusercontent.com',
//     iosBundleId: 'com.bnb.bnbCustomer',
//   );
// }



///dev staging firebase configurations
//
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXJmlR4dh56fpbwn3ZtmTUqrJMxkHkiaI',
    appId: '1:120423255657:web:cc0ea664bdec67897a5cf8',
    messagingSenderId: '120423255657',
    projectId: 'bowandbeautiful-dev',
    authDomain: 'bowandbeautiful-dev.firebaseapp.com',
    databaseURL: 'https://bowandbeautiful-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bowandbeautiful-dev.appspot.com',
    measurementId: 'G-FV760PBJ6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz6MTQ6fitLYV5AZS2SrbWkLLUehgTP0c',
    appId: '1:120423255657:android:f28ec392fc3740537a5cf8',
    messagingSenderId: '120423255657',
    projectId: 'bowandbeautiful-dev',
    databaseURL: 'https://bowandbeautiful-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bowandbeautiful-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHluHIkUp9rs_vILID8JbwQf44iKnd_sE',
    appId: '1:120423255657:ios:a960b4e0b8cd8be57a5cf8',
    messagingSenderId: '120423255657',
    projectId: 'bowandbeautiful-dev',
    databaseURL: 'https://bowandbeautiful-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bowandbeautiful-dev.appspot.com',
    androidClientId: '120423255657-021082iblcqlnar5nc1a11p2v8kd5sl7.apps.googleusercontent.com',
    iosClientId: '120423255657-ahvn5u7th53rqj8ihgb18ooni34ed7e9.apps.googleusercontent.com',
    iosBundleId: 'com.bnb.admin',
  );
}
