// ignore_for_file: constant_identifier_names

class Keys {
  // shared Prefs keys
  static const String isFirstTime = "isFirstTime";
  static const String selectedLang = "selectedLang";
  static const String chat = "chat";
  static const String choosecustomer = "Choose customer";
  static const String nolinkedcustomers = "No linked customers";
  static const String noChats = "No Chats";
  // shared Prefs keys
  static const instrumentSterilization = "instrumentSterilization";
  static const antiCovidMeasures = "anti_covid_measures";
  static const disposableMaterialsOnly = "disposable_materials_only";
  static const womanOwnedBusiness = "woman_owned_business";
  static const coffee = "coffee";
  static const cocktails = "cocktails";
  static const wifi = "wifi";
  static const parking = "parking";
  static const shop = "shop";
  static const childrenRoom = "children_room";
  static const petFriendly = "pet_friendly";
  static const noPet = "no_pet";
  static const accessibilityForPersonsWithReducedMobility = "accessibility_for_persons_with_reducedMobility";
  static const parallelServices = "parallel_services";
  static const medicalPracticeLicense = "medical_practice_license";
  static const bookRestricted = "bookRestricted";
  static const String user = 'user';
  static const String min = "min";
  static const String dollars = "\$";
  static const String uah = "₴";
  static const String sign_in = "sign_in";
  static const String signed_in_successfully = "signed_in_successfully";
  static const String sign_in_failed = "sign_in_failed";
  static const String verification_link_sent = "verification_link_sent";
  static const String profile_details = "profile_details";
  static const String schedule = "schedule";
  static const String services = "services";
  static const String masters = "masters";
  static const String dashboard = "dashboard";
  static const String application_settings = "application_settings";
  static const String client_base = "client_base";
  static const String monthly_calendar = "monthly_calendar";
  static const String daily_calendar = "daily_calendar";
  static const String all = "all";
  static const String manicure_and_pedicure = "manicure_and_pedicure";
  static const String hairdressing = "hairdressing";
  static const String eyebrows_and_eyelashes = "eyebrows_and_eyelashes";
  static const String appointment_details_title = "appointment_details_title";
  static const String appointment_details_line1 = "appointment_details_line1";
  static const String appointment_details_line2 = "appointment_details_line2";
  static const String appointment_details_line3 = "appointment_details_line3";
  static const String appointment_details_line4 = "appointment_details_line4";
  static const String appointment_details_line5 = "appointment_details_line5";
  static const String from = "from";
  static const String to = "to";
  static const String master = "master";
  static const String what_to_do_appointment = "what_to_do_appointment";
  static const String appointment_confirmed = "appointment_confirmed";
  static const String appointment_pending = "appointment_pending";
  static const String appointment_cancelled = "appointment_cancelled";
  static const String order_completed = "order_completed";
  static const String appointment_missed = "appointment_missed";
  static const String checked_in = "checked_in";
  static const String in_process = "in_process";
  static const String appointment_tabbar_line1 = "appointment_tabbar_line1";
  static const String appointment_tabbar_line2 = "appointment_tabbar_line2";
  static const String appointment_tabbar_line3 = "appointment_tabbar_line3";
  static const String appointment_tabbar_line4 = "appointment_tabbar_line4";
  static const String appointment_tabbar_line5 = "appointment_tabbar_line5";
  static const String appointment_tabbar_line6 = "appointment_tabbar_line6";
  static const String appointment_tabbar_line7 = "appointment_tabbar_line7";
  static const String view_visit_history = "view_visit_history";
  static const String noClientAvailable = "noClientAvailable";
  static const String search = "search";
  static const String tomorrow = "tomorrow";
  static const String day = "day";
  static const String home = "home";
  static const String notifications = "notifications";
  static const String createdBooking = "createdBooking";
  static const String changedBooking = "changedBooking";
  static const String cancelledBooking = "cancelledBooking";
  static const String calendar_appointment_line1 = "calendar_appointment_line1";
  static const String duration = "duration";
  static const String h = "h";
  static const String save = "save";
  static const String sign_up = "sign_up";
  static const String next = "next";
  static const String dialogue_line1 = "dialogue_line1";
  static const String dialogue_line2 = "dialogue_line2";
  static const String dialogue_line3 = "dialogue_line3";
  static const String delete_photo_dialogue = "delete_photo_dialogue";
  static const String delete_customer_dialogue = "delete_customer_dialogue";
  static const String delete_category_dialogue = "delete_category_dialogue";
  static const String delete_seat_dialogue = "delete_seat_dialogue";
  static const String delete_service_dialogue = "delete_service_dialogue";
  static const String delete = "delete";
  static const String no = "no";
  static const String yes = "yes";
  static const String description = "description";
  static const String add = "add";
  static const String clients = "clients";
  static const String client = "client";
  static const String appointments = "appointments";
  static const String home_line1 = "home_line1";
  static const String home_line2 = "home_line2";
  static const String category = "category";
  static const String categories = "categories";
  static const String categories_and_services = "categories_and_services";
  static const String please_tap_on_cat = "please_tap_on_cat";
  static const String please_Assign_Price = "please_Assign_Price";
  static const String top_master = "top_master";
  static const String specialist = "specialist";
  static const String trainee = "trainee";
  static const String open = "open";
  static const String closed = "closed";
  static const String break_ = "break";
  static const String update_service = "update_service";
  static const String service_already_present = "service_already_present";
  static const String rename = "rename";
  static const String price_duration_seats = "price_duration_seats";
  static const String for_whom = "for_whom";
  static const String seats = "seats";
  static const String specify_workplace = "specify_workplace";
  static const String specify_seats_available = "specify_seats_available";
  static const String select = "select";
  static const String type_seats_available = "type_seats_available";
  static const String no_seat_available = "no_seat_available";
  static const String add_new_seat_type = "add_new_seat_type";
  static const String this_seat = "this_seat";
  static const String seat_name = "seat_name";
  static const String number_of_seats = "number_of_seats";
  static const String add_new_seat = "add_new_seat";
  static const String seat_dialogue_11 = "seat_dialogue_11";
  static const String seat_dialogue_12 = "seat_dialogue_12";
  static const String alright = "alright";
  static const String no_service_available = "no_service_available";
  static const String assign_seat = "assign_seat";
  static const String selected_seat = "selected_seat";
  static const String select_seat = "select_seat";
  static const String no_seat_selected = "no_seat_selected";
  static const String choose = "Choose";
  static const String name = "name";
  static const String first_name = "first_name";
  static const String last_name = "last_name";
  static const String phone_number = "phone_number";
  static const String phone_number_not_available = "phone_number_not_available";
  static const String email = "email";
  static const String about = "about";
  static const String workingDaysHours = "working_days_hours";
  static const String reviews = "reviews";
  static const String photos_of_works = "photos_of_works";
  static const String new_master_line1 = "new_master_line1";
  static const String description_title = "description_title";
  static const String edit = "edit";
  static const String description_line1 = "description_line1";
  static const String profile_pic_line1 = "profile_pic_line1";
  static const String profile_pic_line2 = "profile_pic_line2";
  static const String changePhoto = "changePhoto";
  static const String editPic = "editPic";
  static const String addPic = "addPic";
  static const String phone = "phone";
  static const String you = "you";
  static const String noNewNotification = "noNewNotification";
  static const String update_master_line1 = "update_master_line1";
  static const String notifications_line1 = "notifications_line1";
  static const String notifications_line2 = "notifications_line2";
  static const String addPhotos = "addPhotos";
  static const String viewed = "viewed";
  static const String details = "details";
  static const String onboarding = "onboarding";
  static const String onboarding_line1 = "onboarding_line1";
  static const String onboarding_line2 = "onboarding_line2";
  static const String onboarding_line3 = "onboarding_line3";
  static const String onboarding_line4 = "onboarding_line4";
  static const String onboarding_line5 = "onboarding_line5";
  static const String onboarding_line6 = "onboarding_line6";
  static const String skip = "skip";
  static const String password = "password";
  static const String registration_line1 = "registration_line1";
  static const String registration_line2 = "registration_line2";
  static const String registration_line3 = "registration_line3";
  static const String registration_line4 = "registration_line4";
  static const String registration_line5 = "registration_line5";
  static const String registration_line6 = "registration_line6";
  static const String registration_line7 = "registration_line7";
  static const String registration_line8 = "registration_line8";
  static const String registration_line9 = "registration_line9";
  static const String registration_line10 = "registration_line10";
  static const String registration_line11 = "registration_line11";
  static const String registration_line12 = "registration_line12";
  static const String registration_line13 = "registration_line13";
  static const String registration_line14 = "registration_line14";
  static const String registration_line15 = "registration_line15";
  static const String registration_line16 = "registration_line16";
  static const String registration_line17 = "registration_line17";
  static const String registration_line18 = "registration_line18";
  static const String registration_line19 = "registration_line19";
  static const String registration_line20 = "registration_line20";
  static const String registration_line21 = "registration_line21";
  static const String registration_line22 = "registration_line22";
  static const String registration_line23 = "registration_line23";
  static const String registration_line24 = "registration_line24";
  static const String registration_line25 = "registration_line25";
  static const String registration_line26 = "registration_line26";
  static const String registration_line27 = "registration_line27";
  static const String registration_line28 = "registration_line28";
  static const String registration_line29 = "registration_line29";
  static const String registration_line30 = "registration_line30";
  static const String registration_line31 = "registration_line31";
  static const String registration_line32 = "registration_line32";
  static const String registration_line33 = "registration_line33";
  static const String registration_line34 = "registration_line34";
  static const String office_number = "office_number";
  static const String street = "street";
  static const String city = "city";
  static const String state = "state";
  static const String registration_line39 = "registration_line39";
  static const String registration_line40 = "registration_line40";
  static const String registration_line41 = "registration_line41";
  static const String registration_line42 = "registration_line42";
  static const String registration_line43 = "registration_line43";
  static const String registration_line44 = "registration_line44";
  static const String registration_line45 = "registration_line45";
  static const String registration_line46 = "registration_line46";
  static const String email_sent_to_reset_password = "email_sent_to_reset_password";
  static const String for_ = "for";
  static const String men = "men";
  static const String women = "women";
  static const String kids = "kids";
  static const String men_women = "men_women";
  static const String january = "january";
  static const String february = "february";
  static const String march = "march";
  static const String april = "april";
  static const String may = "may";
  static const String june = "june";
  static const String july = "july";
  static const String august = "august";
  static const String september = "september";
  static const String october = "october";
  static const String november = "november";
  static const String december = "december";
  static const String hairdresser = "hairdresser";
  static const String service_list_line1 = "service_list_line1";
  static const String service_list_line2 = "service_list_line2";
  static const String service_list_line3 = "service_list_line3";
  static const String service_list_line4 = "service_list_line4";
  static const String service_list_line5 = "service_list_line5";
  static const String service_list_line6 = "service_list_line6";
  static const String service_list_line7 = "service_list_line7";
  static const String service_list_line8 = "service_list_line8";
  static const String salon_available_online = "salon_available_online";
  static const String service = "service";
  static const String price = "price";
  static const String price_and_duration = "price_and_duration";
  static const String view_appointments_line1 = "view_appointments_line1";
  static const String at = "at";
  static const String appointment = "appointment";
  static const String customer = "customer";
  static const String created_at = "created_at";
  static const String members = "members";
  static const String member = "member";
  static const String day_off = "day_off";
  static const String working = "working";
  static const String select_date = "select_date";
  static const String select_time = "select_time";
  static const String new_ = "new";
  static const String new_master = "new_master";
  static const String new_client = "new_client";
  static const String new_service = "new_service";
  static const String cancel = "cancel";
  static const String ok = "ok";
  static const String timeError = "timeError";
  static const String breakError = "breakError";
  static const String workingHours = "workingHours";
  static const String lunch = "lunch";
  static const String seeProfile = "seeProfile";
  static const String language = "language";
  static const String noRating = "noRating";
  static const String historyOfVisits = "historyOfVisits";
  static const String noVisit = "noVisit";
  static const String noReview = "noReview";
  static const String comments = "comments";
  static const String comment = "comment";
  static const String sentAt = "sentAt";
  static const String addReview = "addReview";
  static const String youRatedClient = "youRatedClient";
  static const String note = "note";
  static const String profileSettings = "profileSettings";
  static const String site = "site";
  static const String address = "address";
  static const String showMore = "showMore";
  static const String showLess = "showLess";
  static const String showAll = "showAll";
  static const String itemOfService = "itemOfService";
  static const String itemsOfServices = "itemsOfServices";
  static const String links = "links";
  static const String facebookMessenger = "facebookMessenger";
  static const String viber = "viber";
  static const String telegram = "telegram";
  static const String whatsApp = "whatsApp";
  static const String instagram = "instagram";
  static const String facebookFieldHint = "facebookFieldHint";
  static const String viberFieldHint = "viberFieldHint";
  static const String telegramFieldHint = "telegramFieldHint";
  static const String whatsappFieldHint = "whatsappFieldHint";
  static const String instagramFieldHint = "instagramFieldHint";
  static const String photosOfBestWork = "photosOfBestWork";
  static const String photos = "photos";
  static const String photoInfo = "photoInfo";
  static const String generalSettings = "generalSettings";
  static const String security = "security";
  static const String secureYourAccount = "secureYourAccount";
  static const String changePassword = "changePassword";
  static const String changeLanguage = "changeLanguage";
  static const String notificationSettings = "notificationSettings";
  static const String accountAvailableOnline = "accountAvailableOnline";
  static const String bookingPolicy = "bookingPolicy";
  static const String cancellationPolicy = "cancellationPolicy";
  static const String logOut = "logOut";
  static const String logOutAlert = "logOutAlert";
  static const String theNewClient = "theNewClient";
  static const String successfullyAdded = "successfullyAdded";
  static const String view = "view";
  static const String session = "session";
  static const String custom = "custom";
  static const String weak = "weak";
  static const String operation = "operation";
  static const String account = "account";
  static const String wrong = "wrong";
  static const String expired = "expired";
  static const String missing = "missing";
  static const String credential = "credential";
  static const String errorOccurred = "errorOccurred";
  static const String otpSentTo = "otpSentTo";
  static const String enterOtpAlert = "enterOtpAlert";
  static const String photo_permission_error = "photo_permission_error";
  static const String show_internet_error = "show_internet_error";
  static const String finance = "finance";
  static const String paidFeatures = "paidFeatures";
  static const String unlockPremiumFeatures = "unlockPremiumFeatures";
  static const String paymentHistory = "paymentHistory";
  static const String comingSoon = "comingSoon";
  static const String retry = "retry";
  static const String totalEarned = "totalEarned";
  static const String UKR = "UKR";
  static const String AUS = "AUS";
  static const String BLR = "BLR";
  static const String CAN = "CAN";
  static const String HRV = "HRV";
  static const String GEO = "GEO";
  static const String IND = "IND";
  static const String MDA = "MDA";
  static const String ROU = "ROU";
  static const String SRB = "SRB";
  static const String TUR = "TUR";
  static const String USA = "USA";
  static const String seeDetails = "SeeDetails";
  static const String book = "Book";
  static const String newAppointment = "NewAppointment";
  static const String repeated = "Repeated";
  static const String continue_ = "Continue";
  static const String chooseMaster = "ChooseMaster";
  static const String chooseService = "ChooseService";
  static const String availableTime = "AvailableTime";
  static const String morning = "Morning";
  static const String afternoon = "Afternoon";
  static const String evening = "Evening";
  static const String appointmentFor = "AppointmentFor";
  static const String myself = "Myself";
  static const String anotherPerson = "AnotherPerson";
  static const String clientName = "ClientName";
  static const String clientNumber = "ClientNumber";
  static const String back = "Back";
  static const String noAppointmentsFound = "NoAppointmentsFound";
  static const String okey = "Okey";
  static const String twoHoursBeforeTheAppointment = "TwoHoursBeforeTheAppointment";
  static const String mostPeopleCancelLastMinute = "MostPeopleCancelLastMinute";
  static const String hoursLessBeforeTheAppointment = "24hoursLessBeforeTheAppointment";
  static const String thanksForCanceling = "ThanksForCanceling";
  static const String hoursMoreBeforeTheAppointment = "24hoursMoreBeforeTheAppointment";
  static const String priorWarningThanks = "priorWarningThanks";
  static const String calenderEmpty = "CalenderEmpty";
  static const String allAppointmentsHere = "AllAppointmentsHere";
  static const String goToCategories = "GoToCategories";
  static const String yesCancel = "YesCancel";
  static const String cancelVisit = "CancelVisit";
  static const String nochats = "Nochats";
  static const String sentAnImage = "sentAnImage";
  static const String favourites = "Favourites";
  static const String saveFavourites = "SaveFavourites";
  static const String welcomeback = "Welcomeback";
  static const String recommended = "Recommended";
  static const String filter = "Filter";
  static const String filters = "Filters";
  static const String viewOnMap = "ViewOnMap";
  static const String sort = "Sort";
  static const String completeList = "CompleteList";
  static const String distanceArea = "DistanceArea";
  static const String reset = "Reset";
  static const String apply = "Apply";
  static const String serviceFor = "ServiceFor";
  static const String serviceSpecialist = "ServiceSpecialist";
  static const String onlySaloons = "OnlySaloons";
  static const String onlyMasters = "OnlyMasters";
  static const String youHaveAppointment = "YouHaveAppointment";
  static const String noNotificationsYet = "NoNotificationsYet";
  static const String allNotificationsHere = "AllNotificationsHere";
  static const String getStarted = "GetStarted";
  static const String inviteByPhoneNumber = "InviteByPhoneNumber";
  static const String invite = "Invite";
  static const String inviteSent = "inviteSent";
  static const String ooopsPersonInSystemAlready = "OoopsPersonInSystemAlready";
  static const String friendsInvitation = "FriendsInvitation";
  static const String goodFriendsTakeCare = "GoodFriendsTakeCare";
  static const String inviteFriendsAndGet = "InviteFriendsAndGet";
  static const String forEachonYourBonusAccount = "forEachonYourBonusAccount";
  static const String inviteFriends = "InviteFriends";
  static const String personalLinkDescription = "PersonalLinkDescription";
  static const String receiveNotifications = "ReceiveNotifications";
  static const String notifWhenSignUp = "NotifWhenSignUp";
  static const String bonusAfterThat = "BonusAfterThat";
  static const String getBonuses = "GetBonuses";
  static const String everyInviteWillGet = "EveryInviteWillGet";
  static const String afterSignupYouWillGet = "AfterSignupYouWillGet";
  static const String bczSharingIsCaring = "BczSharingIsCaring";
  static const String spendBonuses = "SpendBonuses";
  static const String useBonusAndEnjoy = "UseBonusAndEnjoy";
  static const String addCards = "AddCards";
  static const String myCards = "MyCards";
  static const String myPayments = "MyPayments";
  static const String historyOfPayments = "HistoryOfPayments";
  static const String cardScan = "CardScan";
  static const String myPreferences = "MyPreferences";
  static const String byService = "byService";
  static const String byGender = "byGender";
  static const String forMan = "ForMan";
  static const String forWoman = "ForWoman";
  static const String iDontCare = "IDontCare";
  static const String notifyTheAppointment = "NotifyTheAppointment";
  static const String oneDay = "oneDay";
  static const String threeDay = "threeDay";
  static const String oneWeek = "oneWeek";
  static const String beforeTheDate = "beforeTheDate";
  static const String settings = "Settings";
  static const String privacyAndSecurity = "PrivacyAndSecurity";
  static const String help = "Help";
  static const String rating = "Rating";
  static const String myBonuses = "MyBonuses";
  static const String yourBonuses = "YourBonuses";
  static const String yourBonusAmount = "YourBonusAmount";
  static const String bonusesHistory = "BonusesHistory";
  static const String forInviting = "forInviting";
  static const String personalInformation = "PersonalInformation";
  static const String dateOfBirth = "DateOfBirth";
  static const String saveChanges = "SaveChanges";
  static const String pickAdate = "PickAdate";
  static const String profile = "Profile";
  static const String myHistoryOfVisits = "MyHistoryOfVisits";
  static const String signUp = "SignUp";
  static const String signIn = "SignIn";
  static const String enterPromoCode = "EnterPromoCode";
  static const String confirm = "confirm";
  static const String doYouHavePromoCode = "DoYouHavePromoCode";
  static const String orSignInWith = "orSignInWith";
  static const String iAgreeToTermsAndConditions = "IAgreeToTermsAndConditions";
  static const String orSignUpWith = "orSignUpWith";
  static const String done = "Done";
  static const String chooseThreeWords = "ChooseThreeWords";
  static const String addYourCardAndGetBonus = "AddYourCardAndGetBonus";
  static const String enableLocationServices = "enableLocationServices";
  static const String allowNotifications = "allowNotifications";
  static const String needYourLocationForContent = "NeedYourLocationForContent";
  static const String turnOnLocation = "TurnOnLocation";
  static const String preferServicesFor = "PreferServicesFor";
  static const String showMeAll = "ShowMeAll";
  static const String whichStatementIsTruerForYou = "WhichStatementIsTruerForYou";
  static const String ipreferTopServices = "IpreferTopServices";
  static const String iPreferTraineeServicews = "IPreferTraineeServicews";
  static const String idontCareGiveMeGoodService = "IdontCareGiveMeGoodService";
  static const String first = "First";
  static const String oneMore = "OneMore";
  static const String itsMiddle = "ItsMiddle";
  static const String andOneMore = "AndOneMore";
  static const String andTheLast = "AndTheLast";
  static const String finish = "Finish";
  static const String letsGeStarted = "LetsGeStarted";
  static const String answerFewQuestions = "AnswerFewQuestions";
  static const String please = "Please";
  static const String letsGo = "LetsGo";
  static const String getNotified = "GetNotified";
  static const String turnOnNotifs = "turnOnNotifs";
  static const String allow = "Allow";
  static const String rateService = "rateService";
  static const String tellUsAaboutMaster = "TellUsAaboutMaster";
  static const String tellUsAbouSalon = "TellUsAbouSalon";
  static const String tellUsSalonMore = "TellUsSalonMore";
  static const String tellUsWhyChose = "TellUsWhyChose";
  static const String useMyAccountForReview = "UseMyAccountForReview";
  static const String useOnlyMyFirstNameWithoutPhoto = "UseOnlyMyFirstNameWithoutPhoto";
  static const String remindMeLater = "RemindMeLater";
  static const String less = "Less";
  static const String bookNow = "BookNow";
  static const String openingHours = "OpeningHours";
  static const String contacts = "Contacts";
  static const String moreReviews = "MoreReviews";
  static const String lessReviews = "LessReviews";
  static const String bestWorks = "BestWorks";
  static const String okayTurnOnLocation = "OkayTurnOnLocation";
  static const String notNow = "NotNow";
  static const String superNowWontMisSuggest = "SuperNowWontMisSuggest";
  static const String queSendReminders = "QueSendReminders";
  static const String yesPlease = "YesPlease";
  static const String noImOk = "NoImOk";
  static const String ifNotYouThenWho = "IfNotYouThenWho";
  static const String indeedLetsLink = "IndeedLetsLink";
  static const String notMeNotNow = "NotMeNotNow";
  static const String tutorial01 = "Tutorial01";
  static const String tutorial02 = "Tutorial02";
  static const String tutorial03 = "Tutorial03";
  static const String tutorial04 = "Tutorial04";
  static const String pleaseSetAnAddress = "PleaseSetAnAddress";
  static const String lastBooked = "LastBooked";
  static const String searchServices = "SearchServices";
  static const String hereWillBeYourSearchResults = "HereWillBeYourSearchResults";
  static const String sortBy = "SortBy";
  static const String lowPriceFirst = "lowPriceFirst";
  static const String highPriceFirst = "highPriceFirst";
  static const String popularFirst = "popularFirst";
  static const String newestFirst = "newestFirst";
  static const String salonOrMasterDeletedYourAppointment = "SalonOrMasterDeletedYourAppointment";
  static const String startConversation = "StartConversation";
  static const String holdCardHere = "HoldCardHere";
  static const String utWillScanAutomatically = "ItWillScanAutomatically";
  static const String oopsThisTimeTaken = "OopsThisTimeTaken";
  static const String protectYourselfCovid = "ProtectYourselfCovid";
  static const String wearAFMask = "WearAFMask";
  static const String washYourFHands = "WashYourFHands";
  static const String avoidCrowdsAndKeepSocialDistance = "AvoidCrowdsAndKeepSocialDistance";
  static const String stayHomeAndContactYourDoctor = "StayHomeAndContactYourDoctor";
  static const String dontForgetToCancelAppointment24Hours = "DontForgetToCancelAppointment24Hours";
  static const String beSafeAndCare = "BeSafeAndCare";
  static const String yesOfCourse = "YesOfCourse";
  static const String yourWishesOrComments = "YourWishesOrComments";
  static const String yhankYouForYourReview = "ThankYouForYourReview";
  static const String removeThisMasterSalonfromYourFavorites = "RemoveThisMasterSalonfromYourFavorites";
  static const String confirmYouWillComePlease = "ConfirmYouWillComePlease";
  static const String imNotComing = "ImNotComing";
  static const String total = "Total";
  static const String makeAppointmentDontForgetBonus = "MakeAppointmentDontForgetBonus";
  static const String linkYourCard = "LinkYourCard";
  static const String link = "Link";
  static const String nowIAmHere = "NowIAmHere";
  static const String appointmentsInAewTaps = "AppointmentsInAewTaps";
  static const String chooseByServicesPriceDistanceRating = "ChooseByServicesPriceDistanceRating";
  static const String seeSalonNMastersArpundYou = "SeeSalonNMastersArpundYou";
  static const String chooseMasterSalonBasedOnRealReviews = "ChooseMasterSalonBasedOnRealReviews";
  static const String dontEverMissAppointmentsWithOurNotifications = "DontEverMissAppointmentsWithOurNotifications";
  static const String ukrainian = "Ukrainian";
  static const String youSureWeMightSuggestYouVariants = "YouSureWeMightSuggestYouVariants";

  static const String salon = "salon";
  static const String specialistStudio = "specialistStudio";
  static const String singleMaster = "singleMaster";
  static const String pleasefillInYourName = "pleasefillInYourName";
  static const String resendVerificationCode = "resendVerificationCode";
}




























































































































// dont delete
//   static const String signIn = 'sign_in';
//   static const String signedInSuccessfully = 'signed_in_successfully';
//   static const String signedInFailed = 'sign_in_failed';
//   static const String verificationLinkSent = 'verification_link_sent';
//   static const String profileDetails = "profile_details";
//   static const String schedule = "schedule";
//   static const String services = "services";
//   static const String mastersSimple = "masters_simple";
//   static const String masters = "masters";
//   static const String dashboard = "dashboard";
//   static const String applicationSettings = "application_settings";
//   static const String clientBase = "client_base";
//   static const String monthlyCalendar = "monthly_calendar";
//   static const String dailyCalendar = "daily_calendar";
//   static const String all = "all";
//   static const String hairdressing = "hairdressing";
//   static const String manicureAndPedicure = "manicure_and_pedicure";
//   static const String eyebrowsAndEyelashes = "eyebrows_and_eyelashes";
//   static const String appointmentDetailsTitle = "appointment_details_title";
//   static const String appointmentDetailsLine1 = "appointment_details_line1";
//   static const String change = "change";
//   static const String appointmentDetailsLine2 = "appointment_details_line2";
//   static const String appointmentDetailsLine3 = "appointment_details_line3";
//   static const String viewVisitHistory = "view_visit_history";
//   static const String appointmentDetailsLine5 = "appointment_details_line5";
//   static const String from = "from";
//   static const String to = "to";
//   static const String master = "master";
//   static const String whatToDoAppointment = "what_to_do_appointment";
//   static const String noSlot = "no_slot";

//   static const String appointmentConfirmed = "appointment_confirmed";
//   static const String appointmentPending = "appointment_pending";
//   static const String appointmentCancelled = "appointment_cancelled";
//   static const String orderCompleted = "order_completed";
//   static const String appointmentMissed = "appointment_missed";
//   static const String checkedIn = "checked_in";
//   static const String inProcess = "in_process";

//   static const String appointmentTabbarLine1 = "appointment_tabbar_line1";
//   static const String appointmentTabbarLine2 = "appointment_tabbar_line2";
//   static const String appointmentTabbarLine3 = "appointment_tabbar_line3";
//   static const String appointmentTabbarLine4 = "appointment_tabbar_line4";
//   static const String appointmentTabbarLine5 = "appointment_tabbar_line5";
//   static const String appointmentTabbarLine6 = "appointment_tabbar_line6";
//   static const String appointmentTabbarLine7 = "appointment_tabbar_line7";
//   static const String noClientAvailable = "noClientAvailable";
//   static const String search = "search";
//   static const String today = "today";
//   static const String tomorrow = "tomorrow";
//   static const String day = "day";
//   static const String home = "home";
//   static const String you = "you";
//   static const String notifications = "notifications";
//   static const String createdBooking = "createdBooking";
//   static const String changedBooking = "changedBooking";
//   static const String cancelledBooking = "cancelledBooking";
//   static const String calendarAppointmentLine1 = "calendar_appointment_line1";
//   static const String duration = "duration";
//   static const String h = "h";
//   static const String timeUnit = "time_unit";
//   static const String currencyUnit = "currency_unit";
//   static const String save = "save";
//   static const String signUp = "sign_up";
//   static const String next = "next";
//   static const String dialogueLine2 = "dialogue_line2";
//   static const String dialogueLine3 = "dialogue_line3";
//   static const String deletePhotoDialogue = "delete_photo_dialogue";
//   static const String deleteCustomerDialogue = "delete_customer_dialogue";
//   static const String deleteMasterDialogue = "delete_master_dialogue";
//   static const String deleteCategoryDialogue = "delete_category_dialogue";
//   static const String addCategoryDialogue = "add_category_dialogue";
//   static const String deleteSeatDialogue = "delete_seat_dialogue";
//   static const String deleteServiceDialogue = "delete_service_dialogue";
//   static const String createSeat = "create_seat";
//   static const String deleteSeat = "delete_seat";

//   static const String delete = "delete";
//   static const String no = "no";
//   static const String yes = "yes";
//   static const String description = "description";
//   static const String add = "add";
//   static const String clients = "clients";
//   static const String client = "client";
//   static const String appointments = "appointments";
//   static const String homeLine1 = "home_line1";
//   static const String homeLine2 = "home_line2";
//   static const String category = "category";
//   static const String addCategory = "add_category";
//   static const String categories = "categories";
//   static const String categoriesAndServices = "categories_and_services";
//   static const String pleaseTapOnCat = "please_tap_on_cat";
//   static const String assignPriceFirst = "assign_price_first";
//   static const String pleaseAssignPrice = "please_Assign_Price";
//   static const String price0Error = "price_0_error";
//   static const String duration0Error = "duration_0_error";
//   static const String pleaseAssignWorkingHours = "please_assign_working_hours";
//   static const String topMaster = "top_master";
//   static const String specialist = "specialist";
//   static const String trainee = "trainee";
//   static const String name = "name";
//   static const String firstName = "first_name";
//   static const String lastName = "last_name";
//   static const String phoneNumber = "phone_number";
//   static const String phoneNumberNotAvailable = "phone_number_not_available";
//   static const String email = "email";
//   static const String about = "about";
//   static const String workingDaysHours = "working_days_hours";
//   static const String reviews = "reviews";
//   static const String photosOfWorks = "photos_of_works";
//   static const String newMasterLine1 = "new_master_line1";
//   static const String descriptionTitle = "description_title";
//   static const String edit = "edit";
//   static const String descriptionLine1 = "description_line1";
//   static const String profilePicLine1 = "profile_pic_line1";
//   static const String profilePicLine2 = "profile_pic_line2";
//   static const String changePhoto = "changePhoto";
//   static const String editPic = "editPic";
//   static const String addPic = "addPic";
//   static const String phone = "phone";
//   static const String noNewNotification = "noNewNotification";
//   static const String updateMasterLine1 = "update_master_line1";
//   static const String notificationsLine1 = "notifications_line1";
//   static const String notificationsLine2 = "notifications_line2";
//   static const String viewed = "viewed";
//   static const String details = "details";
//   static const String onboarding = "onboarding";
//   static const String onboardingLine1 = "onboarding_line1";
//   static const String onboardingLine2 = "onboarding_line2";
//   static const String onboardingLine3 = "onboarding_line3";
//   static const String onboardingLine4 = "onboarding_line4";
//   static const String onboardingLine5 = "onboarding_line5";
//   static const String onboardingLine6 = "onboarding_line6";
//   static const String skip = "skip";
//   static const String password = "password";
//   static const String registrationLine1 = "registration_line1";
//   static const String registrationLine2 = "registration_line2";
//   static const String registrationLine3 = "registration_line3";
//   static const String registrationLine4 = "registration_line4";
//   static const String registrationLine5 = "registration_line5";
//   static const String registrationLine6 = "registration_line6";
//   static const String registrationLine7 = "registration_line7";
//   static const String registrationLine8 = "registration_line8";
//   static const String registrationLine9 = "registration_line9";
//   static const String registrationLine10 = "registration_line10";
//   static const String registrationLine11 = "registration_line11";
//   static const String registrationLine12 = "registration_line12";
//   static const String registrationLine13 = "registration_line13";
//   static const String registrationLine14 = "registration_line14";
//   static const String registrationLine15 = "registration_line15";
//   static const String registrationLine16 = "registration_line16";
//   static const String registrationLine17 = "registration_line17";
//   static const String registrationLine18 = "registration_line18";
//   static const String registrationLine19 = "registration_line19";
//   static const String registrationLine20 = "registration_line20";
//   static const String registrationLine21 = "registration_line21";
//   static const String registrationLine22 = "registration_line22";
//   static const String registrationLine23 = "registration_line23";
//   static const String registrationLine24 = "registration_line24";
//   static const String registrationLine25 = "registration_line25";
//   static const String registrationLine26 = "registration_line26";
//   static const String registrationLine27 = "registration_line27";
//   static const String registrationLine28 = "registration_line28";

//   static const String inviteByEmail = "invite_by_email";
//   static const String inviteByPhone = "invite_by_phone";
//   static const String inviteSuccess = "invite_success";
//   static const String alreadyInvited = "already_invited";
//   static const String invitedToBeTheAdmin = "invited_to_be_the_Admin";
//   static const String acceptInvitation = "accept_invitation";

//   static const String registrationLine29 = "registration_line29";
//   static const String registrationLine30 = "registration_line30";
//   static const String registrationLine31 = "registration_line31";
//   static const String registrationLine32 = "registration_line32";
//   static const String registrationLine33 = "registration_line33";
//   static const String registrationLine34 = "registration_line34";
//   static const String officeNumber = "office_number";
//   static const String street = "street";
//   static const String city = "city";
//   static const String state = "state";
//   static const String registrationLine39 = "registration_line39";
//   static const String setLocationTitle = "setLocationTitle";
//   static const String setLocationSubTitle = "setLocationSubTitle";
//   static const String registrationLine41 = "registration_line41";
//   static const String registrationLine42 = "registration_line42";
//   static const String registrationLine43 = "registration_line43";
//   static const String registrationLine44 = "registration_line44";
//   static const String registrationLine45 = "registration_line45";
//   static const String registrationLine46 = "registration_line46";
//   static const String emailSentToResetPassword = "email_sent_to_reset_password";
//   static const String forKey = "for";
//   static const String men = "men";
//   static const String women = "women";
//   static const String kids = "kids";
//   static const String menWomen = "men_women";
//   static const String january = "january";
//   static const String february = "february";
//   static const String march = "march";
//   static const String april = "april";
//   static const String may = "may";
//   static const String june = "june";
//   static const String july = "july";
//   static const String august = "august";
//   static const String september = "september";
//   static const String october = "october";
//   static const String november = "november";
//   static const String december = "december";
//   static const String hairdresser = "hairdresser";
//   static const String serviceListLine1 = "service_list_line1";
//   static const String serviceListLine2 = "service_list_line2";
//   static const String serviceListLine3 = "service_list_line3";
//   static const String serviceListLine4 = "service_list_line4";
//   static const String serviceListLine5 = "service_list_line5";
//   static const String serviceListLine6 = "service_list_line6";
//   static const String serviceListLine7 = "service_list_line7";
//   static const String serviceListLine8 = "service_list_line8";
//   static const String salonAvailableOnline = "salon_available_online";
//   static const String service = "service";
//   static const String priceAndDuration = "price_and_duration";
//   static const String price = "price";
//   static const String viewAppointmentsLine1 = "view_appointments_line1";
//   static const String at = "at";
//   static const String appointment = "appointment";
//   static const String customer = "customer";
//   static const String createdAt = "created_at";
//   static const String members = "members";
//   static const String member = "member";
//   static const String dayOff = "day_off";
//   static const String working = "working";
//   static const String selectDate = "select_date";
//   static const String selectTime = "select_time";
//   //static const String neww = "new";
//   static const String newMaster = "new_master";
//   static const String newClient = "new_client";
//   static const String newService = "new_service";
//   static const String addNewClient = "add_new_client";
//   static const String addNewMaster = "add_new_master";
//   static const String addNewService = "add_new_service";

//   static const String ok = "ok";
//   static const String done = "done";
//   static const String cancel = "cancel";
//   static const String timeError = "timeError";
//   static const String breakTimeError = "breakError";
//   static const String workingHours = "workingHours";
//   static const String lunch = "lunch";
//   static const String closed = "closed";
//   static const String open = "open";
//   static const String breakKey = "break";
//   static const String updateService = "update_service";
//   static const String serviceAlreadyPresent = "service_already_present";
//   static const String rename = "rename";
//   static const String priceDurationSeats = "price_duration_seats";
//   static const String forWhom = "for_whom";
//   static const String specifyWorkplace = "specify_workplace";
//   static const String seats = "seats";
//   static const String seat = "seat";
//   static const String specifySeatsAvailable = "specify_seats_available";
//   static const String select = "select";
//   static const String typeSeatsAvailable = "type_seats_available";
//   static const String noSeatAvailable = "no_seat_available";
//   static const String addNewSeatType = "add_new_seat_type";
//   static const String thisSeat = "this_seat";
//   static const String seatName = "seat_name";
//   static const String numberOfSeats = "number_of_seats";
//   static const String addNewSeat = "add_new_seat";
//   static const String seatDialogue11 = "seat_dialogue_11";
//   static const String seatDialogue12 = "seat_dialogue_12";
//   static const String alright = "alright";
//   static const String noServiceAvailable = "no_service_available";

//   static const String assignSeat = "assign_seat";
//   static const String selectedSeat = "selected_seat";
//   static const String selectSeat = "select_seat";
//   static const String noSeatSelected = "no_seat_selected";
//   static const String noSeatPresent = "no_seat_present";
//   static const String pleaseCreateSeat = "please_create_seat";

//   static const String addPhotos = "addPhotos";
//   static const String seeProfile = "seeProfile";
//   static const String language = "language";
//   static const String noRating = "noRating";
//   static const String historyOfVisits = "historyOfVisits";
//   static const String noVisit = "noVisit";
//   static const String noReview = "noReview";
//   static const String comment = "comment";
//   static const String comments = "comments";
//   static const String sentAt = "sentAt";
//   static const String addReview = "addReview";
//   static const String youRatedClient = "youRatedClient";
//   static const String note = "note";
//   static const String profileSettings = "profileSettings";
//   static const String site = "site";
//   static const String address = "address";
//   static const String showMore = "showMore";
//   static const String showLess = "showLess";
//   static const String showAll = "showAll";
//   //static const String itemsOfServices = "itemsOfServices";
//   static const String itemOfService = "itemOfService";
//   static const String links = "links";

//   static const String facebookMessenger = "facebookMessenger";
//   static const String viber = "viber";
//   static const String telegram = "telegram";
//   static const String whatsApp = "whatsApp";
//   static const String instagram = "instagram";
//   static const String facebookFieldHint = "facebookFieldHint";
//   static const String viberFieldHint = "viberFieldHint";
//   static const String telegramFieldHint = "telegramFieldHint";
//   static const String whatsappFieldHint = "whatsappFieldHint";
//   static const String instagramFieldHint = "instagramFieldHint";
//   static const String photosOfBestWork = "photosOfBestWork";
//   static const String photos = "photos";
//   static const String photoInfo = "photoInfo";

//   static const String generalSettings = "generalSettings";
//   static const String security = "security";
//   static const String secureYourAccount = "secureYourAccount";
//   static const String changePassword = "changePassword";
//   static const String changeLanguage = "changeLanguage";
//   static const String notificationSettings = "notificationSettings";
//   static const String accountAvailableOnline = "accountAvailableOnline";
//   static const String bookingPolicy = "bookingPolicy";
//   static const String cancellationPolicy = "cancellationPolicy";
//   static const String logOut = "logOut";
//   static const String logOutAlert = "logOutAlert";
//   static const String theNewClient = "theNewClient";
//   static const String successfullyAdded = "successfullyAdded";
//   static const String view = "view";
//   static const String comingSoon = "comingSoon";
//   static const String retry = "retry";

//   static const String sendResetPassword = "send_reset_password";
//   static const String resetPasswordLinkWillSent = "reset_password_link_will_sent";
//   static const String sendLink = "Send_link";
//   static const String resetPasswordLinkSent = "reset_password_link_sent";
//   static const String sendingError = "sending_error";
//   static const String cantChangePassword = "cant_change_password";
//   //for finance screens

//   static const String finance = "finance";
//   static const String paidFeatures = "paidFeatures";
//   static const String unlockPremiumFeatures = "unlockPremiumFeatures";
//   static const String paymentHistory = "paymentHistory";
//   static const String totalEarned = "totalEarned";

//   // error handling
//   static const String errorOccurred = "errorOccurred";
//   static const String otpSentTo = "otpSentTo";
//   static const String enterOtpAlert = "enterOtpAlert";
//   static const String photoPermissionError = "photo_permission_error";
//   static const String showInternetError = "show_internet_error";
//   static const String pleaseVerifyEmail = "please_verify_email";

//   static const String firstNameShort = "first_name_short";
//   static const String firstNameEmpty = "first_name_empty";
//   static const String lastNameShort = "last_name_short";
//   static const String lastNameEmpty = "last_name_empty";
//   static const String phoneNumberEmpty = "phone_number_empty";
//   static const String phoneNumberInvalid = "phone_number_invalid";

//   ///shared prefs keys
//   static const String isFirstTime = "isFirstTime";
//   static const String selectedLang = "selectedLang";
//   static const String chat = "chat";
//   static const String choosecustomer = "Choose customer";
//   static const String choosecustomer = "Choose customer";
//   static const String nolinkedcustomers = "No linked customers";
//   static const String noChats = "No Chats!";

 
  
//   static const String user =  "User";
//   static const String sign_in =  "Sign in";
//   static const String signed_in_successfully =  "Welcome again";
//   static const String sign_in_failed =  "Sign in failed!";
//   static const String verification_link_sent= "A verification link has been sent to your email account!";
//   static const String profile_details =  "Profile Details";
//   static const String schedule=  "Schedule";
//   static const String services =  "Services";
//   static const String masters =  "Masters";
//   static const String dashboard =  "Dashboard";
//   static const String application_settings =  "Application settings";
//   static const String client_base =  "Clients";
//   static const String monthly_calendar =  "Monthly calendar";
//   static const String daily_calendar =  "Daily calendar";
//   static const String all =  "All";
//   static const String hairdressing =  "Hairdressing";
//   static const String manicure_and_pedicure =  "Manicure and pedicure";
//   static const String eyebrows_and_eyelashes = "Eyebrows and eyelashes";
//   static const String appointment_details_title =  "Appointment details";
//   static const String appointment_details_line1 =  "What do you want to do with this appointment?";
//   static const String appointment_details_line2 =  "Change";
//   static const String appointment_details_line3 =  "Cancel";
//   static const String appointment_details_line4 =  "View visit history";
//   static const String appointment_details_line5 = "Call";
//   static const String from = "From";
//   static const String to = "To";
//   static const String master =  "Master";
//   static const String what_to_do_appointment =  "What do you want to do with this appointment?";
//   static const String appointment_confirmed =  "Confirmed";
//   static const String appointment_pending =  "Pending approval";
//   static const String appointment_cancelled = "Cancelled";
//   static const String order_completed =  "Order completed";
//   static const String appointment_missed =  "Appointment Missed";
//   static const String checked_in =  "Checked in";
//   static const String in_process =  "In process";
//   static const String appointment_tabbar_line1 =  "Make an appointment";
//   static const String appointment_tabbar_line2 =  "service";
//   static const String appointment_tabbar_line3 =  "time & master";
//   static const String appointment_tabbar_line4 =  "client";
//   static const String appointment_tabbar_line5 =  "Client's name";
//   static const String appointment_tabbar_line6 =  "No master available";
//   static const String appointment_tabbar_line7 =  "Top master";
//   static const String view_visit_history =  "View visit history";
//   static const String noClientAvailable =  "No client available";
//   static const String search =  "Search";
//   static const String tomorrow =  "Tomorrow";
//   static const String day =  "Day";
//   static const String home =  "Home";
//   static const String notifications =  "Notifications";
//   static const String createdBooking =  " created a booking on ";
//   static const String changedBooking =  " changed a booking to ";
//   static const String cancelledBooking =  " cancelled a booking on ";
//   static const String calendar_appointment_line1 =  "Block the time";
//   static const String duration =  "Duration";
//   static const String h =  "h";
//   static const String min =  "min";
//   static const String uah =  "UAH";
//   static const String save =  "Save";
//   static const String sign_up =  "Sign up";
//   static const String next =  "Next";
//   static const String dialogue_line1 =  "Are you sure you want to ";
//   static const String dialogue_line2 =  "This action cannot be reversed";
//   static const String dialogue_line3 =  "Add description here";
//   static const String delete_photo_dialogue =  "Are you sure you want to delete the photo?";
//   static const String delete_customer_dialogue =  "Are you sure you want to delete customer from your client base?";
//   static const String delete_master_dialogue =  "Are you sure you want to delete this master from your client base?";
//   static const String delete_category_dialogue =  "Are you sure you want to delete this category?";
//   static const String delete_seat_dialogue = "Are you sure you want to delete this seat?";
//   static const String delete_service_dialogue = "Are you sure you want to delete this service?";
//   static const String delete = "Delete";
//   static const String no = "No";
//   static const String yes = "Yes";
//   static const String description = "Description";
//   static const String add = "Add";
//   static const String clients = "Clients";
//   static const String client = "Client";
//   static const String appointments = "Appointments";
//   static const String home_line1 = "Book an appointment";
//   static const String home_line2 = "View appointment";
//   static const String category =  "Category";
//   static const String categories =  "Categories";
//   static const String categories_and_services =  "Categories and services";
//   static const String please_tap_on_cat =  "Please tap on a category to add it to your salon profile";
//   static const String please_Assign_Price =  "Please assign price and duration to all the selected services provided by this particular master!";
//   static const String please_assign_working_hours =  "Please set the salon's working hours in profile settings first";
//   static const String top_master =  "Top master";
//   static const String specialist =  "Specialist";
//   static const String trainee =  "Trainee";
//   static const String open =  "Open";
//   static const String closed =  "Closed";
//   static const String break =  "Break";
//   static const String update_service =  "Update service";
//   static const String service_already_present =  "Service with the same name is already present. Do you want to update it?";
//   static const String rename =  "Rename";
//   static const String price_duration_seats =  "Price, duration and number of seats";
//   static const String for_whom =  "For whom";
//   static const String seats =  "Seats";
//   static const String specify_workplace =  "Specify service workplaces before specifying categories and services";
//   static const String specify_seats_available =  "Specify seats available";
//   static const String select =  "Select";
//   static const String type_seats_available =  "Type of seats available";
//   static const String no_seat_available =  "No seat is available";
//   static const String add_new_seat_type =  "Add new seat type";
//   static const String this_seat =  "this seat";
//   static const String seat_name =  "Seat name";
//   static const String number_of_seats =  "Number of seats";
//   static const String add_new_seat =  "Add new seat";
//   static const String seat_dialogue_11 =  "What do I need to do with seats?";
//   static const String seat_dialogue_12 =  "If you have an equal number of masters and seats (workplaces), we recommend choosing \"by the number of masters\". If several masters share the same workplace, select \"by the number of seats\"\n\nAdd the number of seats you have and name them. This way the system will check the availability of the master and the workplace at a specific time for making an appointment";
//   static const String alright =  "Alright";
//   static const String no_service_available =  "No service available";
//   static const String assign_seat =  "Assign a seat";
//   static const String selected_seat =  "Selected seat";
//   static const String select_seat =  "Select a seat";
//   static const String no_seat_selected =  "No seat selected";
//   static const String chat = "chat";
//   static const String Choose_customer =  "Choose customer";
//   static const String No_linked_customers = "There are no clients in your client base yet. Here you can chat only with people from your base";
//   static const String No_Chats =  "No chats for now. Choose a client to start a dialogue";
//   static const String name =  "name";
//   static const String first_name =  "First name";
//   static const String last_name =  "Last name";
//   static const String phone_number =  "Phone number";
//   static const String phone_number_not_available =  "Phone number is not available";
//   static const String email =  "Email";
//   static const String about =  "About";
//   static const String working_days_hours =  "Working days/hours";
//   static const String reviews =  "Reviews";
//   static const String photos_of_works =  "Photos of works";
//   static const String new_master_line1 =  "This employee is available for booking";
//   static const String description_title =  "About (Add a description)";
//   static const String edit =  "Edit";
//   static const String description_line1 =  "Add a description here!";
//   static const String profile_pic_line1 =  "tel:";
//   static const String profile_pic_line2 =  "Could not launch ";
//   static const String changePhoto =  "Change photo";
//   static const String editPic =  "Edit pic";
//   static const String addPic =  "Add pic";
//   static const String phone =  "Phone";
//   static const String you =  "You";
//   static const String noNewNotification =  "No new notification";
//   static const String update_master_line1 =  "This employee is available for booking";
//   static const String notifications_line1 =  " has requested a booking on ";
//   static const String notifications_line2 =  "View profile";
//   static const String addPhotos =  "Add photos";
//   static const String viewed =  "Viewed";
//   static const String details =  "Details";
//   static const String onboarding =  "Onboarding";
//   static const String onboarding_line1 =  "Enlarge your client base";
//   static const String onboarding_line2 =  "Schedule your appointment easily";
//   static const String onboarding_line3 =  "Have access to all important statistics";
//   static const String onboarding_line4 =  "Stand out with your true rating";
//   static const String onboarding_line5 =  "Have the best clients";
//   static const String onboarding_line6 =  "Get started";
//   static const String skip =  "Skip";
//   static const String password =  "Password";
//   static const String registration_line1 =  "Welcome";
//   static const String registration_line2 =  "Reset password";
//   static const String registration_line3 =  "Enter the email address associated with your account and we'll send you a link to reset your password";
//   static const String registration_line4 =  "Enter email here";
//   static const String registration_line5 =  "Reset";
//   static const String registration_line6 =  "forgot password?";
//   static const String registration_line7 =  "or sign in with";
//   static const String registration_line8 =  "remember me";
//   static const String registration_line9 =  "Hide";
//   static const String registration_line10 =  "User name";
//   static const String registration_line11 =  "I agree to the terms and conditions";
//   static const String registration_line12 =  "Welcome!";
//   static const String registration_line13 =  "Let's get started";
//   static const String registration_line14 =  "Confirmation";
//   static const String registration_line15 =  "A message with the confirmation code has been sent to the number";
//   static const String registration_line16 =  "Confirm";
//   static const String registration_line17 =  "Didn't receive the OTP?";
//   static const String registration_line18 =  "Resend OTP";
//   static const String registration_line19 =  "Check country code and enter phone number";
//   static const String registration_line20 =  "For further use of the application you need to accept the contract";
//   static const String registration_line21 =  "Contract";
//   static const String registration_line22 =  "Conditions and tariffs";
//   static const String registration_line23 =  "Auto payment condition";
//   static const String registration_line24 =  "Cost of accounting functionality";
//   static const String registration_line25 =  "Accept";
//   static const String registration_line26 =  "You can invite another person who will administer the application";
//   static const String registration_line27 =  "Invite with";
//   static const String registration_line28 =  "Invite";
//   static const String registration_line29 =  "I don’t need this option now";
//   static const String registration_line30 =  "Tell us more about you or your company";
//   static const String registration_line31 =  "Salon";
//   static const String registration_line32 =  "Single master";
//   static const String registration_line33 =  "Salon name";
//   static const String registration_line34 =  "Your name";
//   static const String office_number =  "Office Number & floor (optional)";
//   static const String street =  "Area / Street / Sector";
//   static const String city =  "Town / City";
//   static const String state =  "State / Province";
//   static const String registration_line39 =  "Use current location";
//   static const String registration_line40 =  "Locate your salon on the map";
//   static const String registration_line41 =  "Select location";
//   static const String registration_line42 =  "What categories of services do you provide?";
//   static const String registration_line43 =  "Who do you provide services for?";
//   static const String registration_line44 =  "Choose services for men";
//   static const String registration_line45 =  "I'll do it later";
//   static const String registration_line46 =  "Choose services for women";
//   static const String email_sent_to_reset_password =  "Email has been sent on your registered email address";
//   static const String for =  "For";
//   static const String men =  "men";
//   static const String women =  "women";
//   static const String kids =  "kids";
//   static const String men_women =  "men and women";
//   static const String january =  "January";
//   static const String february =  "February";
//   static const String march =  "March";
//   static const String april =  "April";
//   static const String may =  "May";
//   static const String june =  "June";
//   static const String july =  "July";
//   static const String august =  "August";
//   static const String september =  "September";
//   static const String october =  "October";
//   static const String november =  "November";
//   static const String december =  "December";
//   static const String hairdresser =  "Hairdresser";
//   static const String service_list_line1 =  "cannot delete salon service before creating it";
//   static const String service_list_line2 =  "add new service";
//   static const String service_list_line3 =  "All services";
//   static const String service_list_line4 =  "Price and duration";
//   static const String service_list_line5 =  "one price";
//   static const String service_list_line6 =  "by master skill level";
//   static const String service_list_line7 =  "one duration";
//   static const String service_list_line8 =  "This service will be available online";
//   static const String salon_available_online =  "Salon will be available online";
//   static const String service =  "Service";
//   static const String price =  "Price";
//   static const String price_and_duration =  "Price and duration";
//   static const String view_appointments_line1 =  "Master doesn't exist";
//   static const String at =  "at";
//   static const String appointment =  "Appointment";
//   static const String customer =  "Customer";
//   static const String created_at =  "Created at";
//   static const String members =  "members";
//   static const String member =  "member";
//   static const String day_off =  "Day off";
//   static const String working =  "Working";
//   static const String select_date =  "Select a date";
//   static const String select_time =  "Select time";
//   static const String new_ =  "New";
//   static const String new_master =  "New master";
//   static const String new_client =  "New client";
//   static const String new_service =  "New service";
//   static const String cancel =  "Cancel";
//   static const String ok =  "ok";
//   static const String timeError =  "Whoops! Time seems to be invalid";
//   static const String breakError =  "Whoops! Break time seems to be invalid";
//   static const String workingHours =  "Working hours";
//   static const String lunch =  "Break";
//   static const String seeProfile =  "See profile";
//   static const String language =  "Language";
//   static const String noRating =  "No rating";
//   static const String historyOfVisits =  "History of visits";
//   static const String noVisit =  "No visits available";
//   static const String noReview =  "No review";
//   static const String comments =  "comments";
//   static const String "comment": "comment";
//   static const String "sentAt": "sent at";
//   static const String "addReview": "add a review";
//   static const String "youRatedClient": "You rated the client";
//   static const String "note": "Note";
//   static const String "profileSettings": "Profile settings";
//   static const String "site": "site";
//   static const String "address": "address";
//   static const String "showMore": "Show more";
//   static const String "showLess": "Show less";
//   static const String "showAll": "Show all";
//   static const String "itemOfService": "service";
//   static const String "itemsOfServices": "services";
//   static const String "links": "Links";
//   static const String "facebookMessenger": "Facebook (messenger)";
//   static const String "viber": "Viber";
//   static const String "telegram": "Telegram";
//   static const String "whatsApp": "Whatsapp";
//   static const String "instagram": "Instagram";
//   static const String "facebookFieldHint": "Add facebook messenger link";
//   static const String "viberFieldHint": "Add viber number";
//   static const String "telegramFieldHint": "Add telegram number";
//   static const String "whatsappFieldHint": "Add whatsapp number";
//   static const String "instagramFieldHint": "Add instagram profile link";
//   static const String "photosOfBestWork": "photos of best works (up to 10 photos)";
//   static const String "photos": "Photos";
//   static const String "photoInfo": "these photos will be shown on the main screen of your profile page";
//   static const String "generalSettings": "General settings";
//   static const String "security": "Security";
//   static const String "secureYourAccount": "Secure your account with two-factor authentication";
//   static const String "changePassword": "Change password";
//   static const String "changeLanguage": "Change language";
//   static const String "notificationSettings": "Notification settings";
//   static const String "accountAvailableOnline": "Account is visible to users";
//   static const String "bookingPolicy": "Booking Policy";
//   static const String "cancellationPolicy": "Cancellation Policy";
//   static const String "logOut": "Log out";
//   static const String "logOutAlert": "Are you sure you want to log out?";
//   static const String "theNewClient": "The new client";
//   static const String "successfullyAdded": "successfully added to the client base";
//   static const String "view": "View";
//   static const String "session-expired": "The sms code has expired. Please re-send the verification code to try again.";
//   static const String "custom-token-mismatch": "Something went wrong";
//   static const String "invalid-custom-token": "Something went wrong";
//   static const String "user-disabled": "Your access have been disabled temporarily, please reach out to the admin";
//   static const String "user-not-found": "No user found";
//   static const String "weak-password": "Password is too weak";
//   static const String "email-already-in-use": "This email is already in use";
//   static const String "invalid-email": "Email seems to be invalid";
//   static const String "operation-not-allowed": "Email has been blocked, please contact admin";
//   static const String "account-exists-with-different-credential": "Account with this email address already exists";
//   static const String "invalid-credential": "Credentials are not valid";
//   static const String "wrong-password": "Password is incorrect";
//   static const String "invalid-verification-id": "Password is incorrect";
//   static const String "expired-action-code": "OTP has expired, please send a new one again";
//   static const String "invalid-action-code": "OTP has expired, please send a new one again";
//   static const String "invalid-phone-number": "Phone number is not valid";
//   static const String "missing-client-identifier": "Please try again and fill reCAPTCHA on your  web browser";
//   static const String "invalid-verification-code": "OTP is incorrect";
//   static const String "credential-already-in-use": "Phone number is already in use";
//   static const String "errorOccurred": "Error occurred\nPlease try again!";
//   static const String "otpSentTo": "OTP sent again to";
//   static const String "enterOtpAlert": "Please enter the OTP first!";
//   static const String "photo_permission_error": "Don't have permission to access photos";
//   static const String "show_internet_error": "Error occurred ! Please check your internet connection and try again.";
//   static const String "finance": "Finance";
//   static const String "paidFeatures": "Paid features";
//   static const String "unlockPremiumFeatures": "Unlock premium features";
//   static const String "paymentHistory": "Payment history";
//   static const String "comingSoon": "Coming soon!";
//   static const String "retry": "Retry";
//   static const String "totalEarned": "Total earned";
//   static const String "UKR": "Ukraine";
//   static const String "AUS": "Australia";
//   static const String "BLR": "Belarus";
//   static const String "CAN": "Canada";
//   static const String "HRV": "Croatia";
//   static const String "GEO": "Georgia";
//   static const String "IND": "India";
//   static const String "MDA": "Moldova, Republic of";
//   static const String "ROU": "Romania";
//   static const String "SRB": "Serbia";
//   static const String "TUR": "Turkey";
//   static const String "USA": "United States";
//   static const String "See Details": "See Details";
//   static const String "Book": "Book";
//   static const String "New Appointment": "New Appointment";
//   static const String "Repeated": "Repeated";
//   static const String "Continue": "Continue";
//   static const String "Choose a master": "Choose a master";
//   static const String "Choose a service or services": "Choose one or several services";
//   static const String "Available time": "Available time";
//   static const String "Morning": "Morning";
//   static const String "Afternoon": "Afternoon";
//   static const String "Evening": "Evening";
//   static const String "Appointment for": "Appointment for";
//   static const String "Myself": "Myself";
//   static const String "Another person": "Another person";
//   static const String "Client name": "Person’s full name";
//   static const String "Client number": "His or her phone number";
//   static const String "Back": "Back";
//   static const String "No Appointments found !": "No Appointments found!";
//   static const String "Okey": "Okay";
//   static const String "Two or less hours before the appointment": "Two or less hours before the appointment";
//   static const String "Most people cancel at the last minute in two cases: either they forgot or something happened. So we hope you are safe and sound. If you forgot, make sure you turn your notification on. Take care and try to warn your master earlier next time!": "Most people cancel at the last minute in two cases: either they forgot or something happened. So we hope you are safe and sound. If you forgot, make sure you turn your notification on. Take care and try to warn your master earlier next time!";
//   static const String "Less than 24 hours before the appointment": "Less than 24 hours before the appointment";
//   static const String "Life is unpredictable, we know. Thanks for canceling. If next time you do it at least 1 day before – you'll put a coin in your karma bank and others will have a chance to book a service instead of you 🙂": "Life is unpredictable, we know. Thanks for canceling. If next time you do it at least 1 day before – you'll put a coin in your karma bank and others will have a chance to book a service instead of you 🙂";
//   static const String "More than 24 hours before the appointment": "More than 24 hours before the appointment";
//   static const String "It’s a pity your plans have changed. Thank you for a prior warning. You just put a coin in your karma bank !": "It’s a pity your plans have changed. Thank you for a prior warning. You just put a coin in your karma bank !";
//   static const String "Your calendar is\nempty yet": "Your calendar is empty yet";
//   static const String "Choose a service and a master. All your booked apointments will be here.": "Choose a service and a master. All your booked apointments will be here";
//   static const String "Go to categories": "Go to categories";
//   static const String "Yes Cancel": "Yes, cancel";
//   static const String "Are you sure you want to cancel your visit ?": "Are you sure you want to cancel your visit?";
//   static const String "Cancel Visit": "Cancel visit";
//   static const String "Address": "Address";
//   static const String "Chat": "Chat";
//   static const String "No chats!!": "No chats yet";
//   static const String "sent an image": "sent an image";
//   static const String "Favourites": "Favourites";
//   static const String "Save salons and masters you like by tapping on heart": "Save salons and masters you like by tapping on ❤️";
//   static const String "Welcome back": "Welcome back";
//   static const String "Recommended": "Recommended";
//   static const String "Filter": "Filter";
//   static const String "Filters": "Filters";
//   static const String "View on map": "View on map";
//   static const String "Sort": "Sort";
//   static const String "Complete List": "Complete List";
//   static const String "Distance Area": "Distance Area";
//   static const String "Reset": "Reset";
//   static const String "Apply": "Apply";
//   static const String "Service for": "Service for";
//   static const String "All": "All";
//   static const String "Men": "Men";
//   static const String "Women": "Women";
//   static const String "Price,": "Price,";
//   static const String "Service specialist": "Service specialist";
//   static const String "Only Saloons": "Only salons";
//   static const String "Only masters": "Only masters";
//   static const String "Tomorrow": "Tomorrow";
//   static const String "You Have an appointment": "You have an appointment";
//   static const String "Notifications": "Notifications";
//   static const String "No Notifications Yet": "No notifications yet";
//   static const String "All your notifications will be here: from upcoming appointments to bonuses updates": "All your notifications will be here: from upcoming appointments to bonuses updates";
//   static const String "Get Started": "Get started";
//   static const String "Next": "Next";
//   static const String "Invite by phone number": "Invite by phone number";
//   static const String "Invite": "Invite";
//   static const String "Your invite has been sent successfully": "Your invitation has been sent successfully";
//   static const String "Ooops, we have that person in the system already": "Ooops, we have that person in the system already";
//   static const String "Friends Invitation": "Friends Invitation";
//   static const String "Good friends take care of each other 😊": "Good friends take care of each other 😊";
//   static const String "Invite friends and get": "Invite friends and get";
//   static const String "for each on your bonus account!": "for each on your bonus account!";
//   static const String "Invite Friends": "Invite Friends";
//   static const String "You have a personal referral link for inviting friends to join bnb. Just enter friend’s phone number and we will send them an unique registration code": "You have a personal referral link for inviting friends to join bnb. Just enter friend’s phone number and we will send them a unique registration code";
//   static const String "Receive notifications": "Receive notifications";
//   static const String "We will notify you when your friend signs up and give you a ": "We will notify you when your friend signs up and give you a ";
//   static const String "bonus after that": "bonus after that";
//   static const String "Get bonuses": "Get bonuses";
//   static const String "Every time you invite friends to experience self-care with us, they will get ": "Every time you invite friends to experience self-care with us, they will get ";
//   static const String "after signing up. You will also get ₴": "after signing up. You will also get ₴";
//   static const String "for each invited friend, because sharing is caring": "for each invited friend, because sharing is caring";
//   static const String "Spend bonuses": "Spend bonuses";
//   static const String "Use bonuses while paying for services online: pay part of the total sum with your bonus account and enjoy your time with bnb!": "Use bonuses while paying for services online: pay part of the total sum with your bonus account and enjoy your time with bnb!";
//   static const String "Add cards": "Add cards";
//   static const String "My cards": "My cards";
//   static const String "My Payments": "My Payments";
//   static const String "My Cards": "My Cards";
//   static const String "History of Payments": "History of Payments";
//   static const String "Card Scan": "Card scan";
//   static const String "Language": "Language";
//   static const String "My Preferences": "My Preferences";
//   static const String "by Service": "by service";
//   static const String "by Gender": "by gender";
//   static const String "For Man": "For man";
//   static const String "For Woman": "For woman";
//   static const String "I Don't Care": "For all";
//   static const String "Notification Settings": "Notification Settings";
//   static const String "Notify the appointment ": "Notify of the appointment ";
//   static const String "one day ": "one day ";
//   static const String "three day ": "three day ";
//   static const String "one week ": "one week ";
//   static const String "before the date:": "before the date:";
//   static const String "Settings": "Settings";
//   static const String "Privacy and Security": "Privacy and Security";
//   static const String "Help": "Help";
//   static const String "About": "About";
//   static const String "History of visits": "History of visits";
//   static const String "Rating:": "Rating:";
//   static const String "My Bonuses": "My Bonuses";
//   static const String "Your Bonuses:": "Your Bonuses:";
//   static const String "Your Bonus Amount:": "Your Bonus Amount:";
//   static const String "Bonuses History": "Bonuses History";
//   static const String "for inviting": "for inviting";
//   static const String "Personal Information": "Personal Information";
//   static const String "Date of birth": "Date of birth";
//   static const String "Save Changes ?": "Save Changes?";
//   static const String "Pick a date": "Pick a date";
//   static const String "Select": "Select";
//   static const String "Profile": "Profile";
//   static const String "My history of visits": "My history of visits";
//   static const String "Sign up": "Sign up";
//   static const String "Sign in": "Sign in";
//   static const String "Enter promo code": "Enter registration code";
//   static const String "confirm": "confirm";
//   static const String "Do you have promo code?": "Do you have registration code?";
//   static const String "Yes": "Yes";
//   static const String "No": "No";
//   static const String "Password": "Password";
//   static const String "or sign in with": "or sign in with";
//   static const String "I agree to terms and conditions": "I agree to terms and conditions";
//   static const String "or sign up with": "or sign up with";
//   static const String "Done !": "Done!";
//   static const String "Choose at least three words describing your preferences": "Choose at least 3 categories of services you use the most often";
//   static const String "Add your card to pay online and get bonuses": "Add your card to pay online and get bonuses";
//   static const String "To see the nearest salons and masters, please enable location services": "To see the nearest salons and masters, please enable location services";
//   static const String "To receive reminders of your upcoming appointments, please allow notifications": "To receive reminders of your upcoming appointments, please allow notifications";
//   static const String "We need to know where you are so we can show what we have reviewed around you": "We need to know where you are so we can show what we have reviewed around you";
//   static const String "Turn on location": "Turn on location";
//   static const String "Prefer services for": "Prefer services for";
//   static const String "I don't care": "show me all";
//   static const String "Which statement is truer for you ?": "What would you choose?";
//   static const String "I prefer services from top saloons and top masters only": "I prefer services from top salons and top masters only";
//   static const String "I will gladly receive a service from a trainee too": "I will gladly receive a service from a trainee too";
//   static const String "I don't care about master's salon_home lavel if they provide good service": "I don't care about level of salons or masters if they provide high-quality service";
//   static const String "First...": "First...";
//   static const String "One more...": "One more...";
//   static const String "It's middle...": "It's middle...";
//   static const String "And one more...": "And one more...";
//   static const String "And the last...": "And the last...";
//   static const String "🎉  Finish !": "🎉  Finish ";
//   static const String "Let's get started !": "Let's get started!";
//   static const String "Answer a few questions. It will help us understand what to suggest you": "Answer a few questions. It will help us understand what to suggest to you";
//   static const String "Please?": "Please?";
//   static const String "Let's go !": "Let's go!";
//   static const String "Get notified": "Get notified";
//   static const String "turn on notifications to receive notifications about your bookings and activity": "turn on notifications to receive notifications about your bookings and activity";
//   static const String "Allow": "Allow";
//   static const String "How do you rate the service?": "How do you rate the service?";
//   static const String "Tell us a bit more about the master": "Tell us a bit more about the master";
//   static const String "And what about the salon?": "And what about the salon?";
//   static const String "Tell us a bit more about the salon": "Tell us a bit more about the salon";
//   static const String "Tell us a bit more about why you chose 4": "Tell us a bit more about why you chose 4";
//   static const String "Use my account for review": "Use my account for review";
//   static const String "Use only my first name without photo": "Use only my first name without photo";
//   static const String "Remind Me Later": "Remind Me Later";
//   static const String "Home": "Home";
//   static const String "...Read More": "...Read More";
//   static const String "Less": "Less";
//   static const String "Book Now": "Book Now";
//   static const String "Opening hours": "Opening hours";
//   static const String "Contacts": "Contacts";
//   static const String "Reviews": "Reviews";
//   static const String "More Reviews": "More Reviews";
//   static const String "Less Reviews": "Less Reviews";
//   static const String "BestWorks": "BestWorks";
//   static const String "Okay, turn on location": "Okay, turn on location";
//   static const String "Not now": "Not now";
//   static const String "Super! Now we won't suggest you variants from far-district lands :)": "Super! Now we won't suggest you variants from far-district lands :)";
//   static const String "Cool! From now on you might forget some birthdays, but appointments you won't :)": "Cool! From now on you might forget some birthdays, but appointments you won't :)";
//   static const String "People forget over 1460 things in a year. Maybe you want us to send reminders?": "People forget over 1460 things in a year. Maybe you want us to send reminders?";
//   static const String "Yes, please": "Yes, please";
//   static const String "No, I'm ok": "No, I'm ok";
//   static const String "If not you, then who...If not now, then when...": "If not you, then who...If not now, then when...";
//   static const String "Indeed, let's link": "Indeed, let's link";
//   static const String "Not me, not now": "Not me, not now";
//   static const String "Tutorial01": "Search for salons and service specialist on the map";
//   static const String "Tutorial02": "Сhoose the required category of services here. Swipe left or use arrow to see all categories at once";
//   static const String "Tutorial03": "All your upcoming appointments in the calendar";
//   static const String "Tutorial04": "All your notifications are here ";
//   static const String "Please, set an address. Search results will be more relevant": "Please, set your location. Search results will be more relevant";
//   static const String "Last booked": "Last booked";
//   static const String "Search services, salons, masters": "Search services, salons, masters";
//   static const String "Here will be your search results": "Here will be your  search results";
//   static const String "Sort by": "Sort by";
//   static const String "low price first": "low price first";
//   static const String "high price first": "high price first";
//   static const String "popular first": "popular first";
//   static const String "newest first": "newest first";
//   static const String "Salon or master deleted your appointment": "Salon or master canceled your appointment";
//   static const String "Start conversation": "Start conversation";
//   static const String "Hold card here": "Hold card here";
//   static const String "It will scan automatically": "It will scan automatically";
//   static const String "Oops, this time is already taken! Choose another time": "Oops, this time is already taken! Choose another time";
//   static const String "Protect yourself and others during Covid-19 pandemic:": "Protect yourself and others during Covid-19 pandemic:";
//   static const String "Wear a mask over your nose and mouth and secure it under your chin.": "Wear a mask over your nose and mouth and secure it under your chin";
//   static const String "Wash your hands with soap and water for at least 60 sec or use hand sanitizer if they aren’t available": "Wash your hands with soap and water for at least 20 sec or use hand sanitizer if they aren’t available";
//   static const String "Avoid crowds and keep social distance": "Avoid crowds and keep social distance";
//   static const String "If you are unwell, stay home and contact your doctor": "If you are unwell, stay home and contact your doctor";
//   static const String "And don’t forget to cancel your appointment, preferably not later than 24 hours before it takes place": "And don’t forget to cancel your appointment preferably not later than 24 hours before it takes place";
//   static const String "Be safe and care!": "Be safe and care!";
//   static const String "Yes, of course": "Yes, of course";
//   static const String "Your wishes or comments": "Your wishes or comments";
//   static const String "Thank you for your review!": "Thank you for your review!";
//   static const String "Remove this master/salon from your favorites?": "Remove this master/salon from your favorites?";
//   static const String "Confirm you will come, please": "Confirm you will come, please";
//   static const String "I’m not coming": "I’m not coming";
//   static const String "Total:": "Total:";
//   static const String "Now you can make your first bnb appointment.Enjoy it and don't forget to use your bonuses!": "Now you can make your first bnb appointment. Enjoy it and don't forget to use your bonuses!";
//   static const String "Link your card": "Link your card";
//   static const String "Link": "Link";
//   static const String "Now I am here": "Now I am here";
//   static const String "Appointments in a few taps": "Appointments in a few taps";
//   static const String "Choose by services, price, distance, rating": "Choose by services, price, distance, rating";
//   static const String "See salons and masters around you": "See salons and masters around you";
//   static const String "Choose master or salon based on real reviews": "Choose master or salon based on real reviews";
//   static const String "Don’t ever miss appointments with our notifications": "Don’t ever miss appointments with our notifications";
//   static const String "Ukrainian": "Ukrainian";
//   static const String "You sure? We might suggest you variants from far-district lands then :(": "You sure? We might suggest you variants from far-district lands then :(;
//   }