List<Map<String,String>> salonFeatures = [
    { "covidVaccinated" : "Covid Vaccinated"},
  {"masterWithHearingDisability ": "Master With Hearing Disability"},
  {"masterWithSpeechDisability ": "Master With Speech Disability"},
  {"medicalDegree" : "Medical Degree"},
  {"instrumentsSterilization":  "Instruments Sterilization"},
  {"antiCovidMeasures" : "Anti Covid Measures"},
  {"disposableMaterialsOnly" : "Disposable Materials Only"},
  {"coffee" : "Coffee"},
  {"wifi ": "Wifi"},
  {"ownOffice" : "Own Office"},
  {"parking" : "Parking"},
  {"masterWithHearingDisability" : "Master With Hearing Disability"},
  {"petFriendly": "Pet Friendly"},
  {"noPets": "No Pets"},
  {"accessibilityForPersonsWithReducedMobility ":
    "Accessibility For Persons With ReducedMobility"},
];
List<Map<String,String>> masterFeatures = [
 {"instrumentsSterilization" : "Instrument Sterilization"},
{"antiCovidMeasures":"Anti Covid Measures"},
{"disposableMaterialsOnly":"Disposable Materials Only"},
{"womanOwnedBusiness":"Woman Owned Business"},
{"coffee":"Coffee"},
{"cocktails":"Cocktails"},
{"wifi":"Wifi"},
{"parking":"Parking"},
{"shop":"Shop"},
{"childrenRoom":"Children Room"},
{"petFriend":"Pet Friendly"},
{"noPets":"No Pet"},
{"accessibilityForPersonsWithReducedMobility":"Accessibility For Persons With ReducedMobility"},
{"parallelService":"Parallel Service"},
{"medicalPracticeLicense ":  "Medical Practice License"},
];