List<Map<String,String>> salonFeatures = [
    { "covidVaccinated" : "Covid Vaccinated"},
  {"masterWithHearingDisability": "Master With Hearing Disability"},
  {"masterWithSpeechDisability": "Master With Speech Disability"},
  {"medicalDegree" : "Medical Degree"},
  {"instrumentSterilization":  "Instruments Sterilization"},
  {"antiCovidMeasures" : "Anti Covid Measures"},
  {"disposableMaterialsOnly" : "Disposable Materials Only"},
  {"coffee" : "Coffee"},
  {"cocktails":"cocktails"},
  {"shop":"shop"},
  {"parallelService":"Parallel Service"},
  {"childrenRoom":"Children Room"},
  {"wifi": "Wifi"},
  {"ownOffice" : "Own Office"},
{"womanOwnedBusiness":"Woman Owned Business"},
  {"parking" : "Parking"},
  {"masterWithHearingDisability" : "Master With Hearing Disability"},
  {"petFriendly": "Pet Friendly"},
  {"noPet": "No Pets"},
  {"medicalPracticeLicense":"Medical Practice License"},
  {"accessibilityForPersonsWithReducedMobility":
    "Accessibility For Persons With ReducedMobility"},
];

List<Map<String,String>> ukSalonFeatures = [
  { "covidVaccinated" : "Ковід Вакцинований"},
  {"masterWithHearingDisability ": "Майстер з вадами слуху"},
  {"masterWithSpeechDisability ": "Майстер з вадами мовлення"},
  {"medicalDegree" : "Медичний ступінь"},
  {"instrumentSterilization":  "Стерилізація інструментів"},
  {"antiCovidMeasures" : "Антиковідні заходи"},
  {"disposableMaterialsOnly" : "Лише одноразові матеріали"},
  {"coffee" : "кава"},
  {"wifi": "Wi-Fi"},
  {"ownOffice" : "Власний кабінет"},
  {"parking" : "Паркінг"},
  {"masterWithHearingDisability" : "Майстер з вадами слуху"},
  {"petFriendly": "Допускається розміщення з домашніми тваринами"},
  {"noPet": "Без домашніх тварин"},
  {"accessibilityForPersonsWithReducedMobility":
  "Доступність для осіб з обмеженими можливостями пересування"},
  {"medicalPracticeLicense":  "Ліцензія на медичну практику"},
];

List<Map<String,String>> masterFeatures = [
  {"masterWithHearingDisability": "Master With Hearing Disability"},
  {"masterWithSpeechDisability":  "Master With Speech Disability"},
 {"instrumentsSterilization":"Instrument Sterilization"},
{"antiCovidMeasures":"Anti Covid Measures"},
{"disposableMaterialsOnly":"Disposable Materials Only"},
{"womanOwnedBusiness":"Woman Owned Business"},
{"coffee": "Coffee"},
{"cocktails": "Cocktails"},
  {"ownOffice" :"Own Office"},
  {"medicalDegree" :"Medical Degree"},
{"wifi": "Wifi"},
{"parking":  "Parking"},
{"shop":"Shop"},
{"childrenRoom":"Children Room"},
{"petFriendly":"Pet Friendly"},
{"noPets":"No Pet"},
  { "covidVaccinated" :"Covid Vaccinated"},
{"accessibilityForPersonsWithReducedMobility":"Accessibility For Persons With ReducedMobility"},
{"parallelService":"Parallel Service"},
{"medicalPracticeLicense":"Medical Practice License"},
];

List<Map<String,String>> ukMasterFeatures = [
  {"masterWithHearingDisability": "Майстер з порушення слуху"},
  {"masterWithSpeechDisability":  "Майстер з порушенням мовлення"},
  {"ownOffice" :"Власний кабінет"},
  {"instrumentsSterilization" : "Стерилізація інструментів"},
  {"antiCovidMeasures":"Антиковідні заходи"},
  {"disposableMaterialsOnly":"Лише одноразові матеріали"},
  {"womanOwnedBusiness":"Жіночий бізнес"},
  {"coffee":"Кава/Чай"},
  {"medicalDegree" :"Медична освіта"},
  {"cocktails":"Коктейлі"},
  { "covidVaccinated" :"Вакцинованість проти Covid-19"},
  {"wifi":"Wi-Fi"},
  {"parking":"Паркінг"},
  {"shop":"Магазин"},
  {"childrenRoom":"Дитяча кімната"},
  {"petFriendly":"Допускається розміщення з домашніми тваринами"},
  {"noPets":"Без тварин"},
  {"accessibilityForPersonsWithReducedMobility":"Доступність для осіб з обмеженими можливостями пересування"},
  {"parallelService":"Паралельний сервіс"},
  {"medicalPracticeLicense ":  "Ліцензія на медичну практику"},
];